/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated.ledger'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated.inventory'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated.assets'
import { Route as AuthenticatedAmendmentsRouteImport } from './routes/_authenticated.amendments'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated.vendors.index'
import { Route as AuthenticatedMaterialsIndexRouteImport } from './routes/_authenticated.materials.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated.invoices.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated.vendors.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated.invoices.new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated.invoices.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated.clients.$id'
import { Route as AuthenticatedVendorsGrnNewRouteImport } from './routes/_authenticated.vendors.grn.new'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAmendmentsRoute = AuthenticatedAmendmentsRouteImport.update({
  id: '/amendments',
  path: '/amendments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialsIndexRoute =
  AuthenticatedMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsGrnNewRoute =
  AuthenticatedVendorsGrnNewRouteImport.update({
    id: '/vendors/grn/new',
    path: '/vendors/grn/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/amendments': typeof AuthenticatedAmendmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/vendors/grn/new': typeof AuthenticatedVendorsGrnNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/amendments': typeof AuthenticatedAmendmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/vendors/grn/new': typeof AuthenticatedVendorsGrnNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/amendments': typeof AuthenticatedAmendmentsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/vendors/grn/new': typeof AuthenticatedVendorsGrnNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/amendments'
    | '/assets'
    | '/inventory'
    | '/ledger'
    | '/reports'
    | '/settings'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/vendors/$id'
    | '/clients/'
    | '/invoices/'
    | '/materials/'
    | '/vendors/'
    | '/vendors/grn/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/amendments'
    | '/assets'
    | '/inventory'
    | '/ledger'
    | '/reports'
    | '/settings'
    | '/'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/vendors/$id'
    | '/clients'
    | '/invoices'
    | '/materials'
    | '/vendors'
    | '/vendors/grn/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/amendments'
    | '/_authenticated/assets'
    | '/_authenticated/inventory'
    | '/_authenticated/ledger'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/clients/'
    | '/_authenticated/invoices/'
    | '/_authenticated/materials/'
    | '/_authenticated/vendors/'
    | '/_authenticated/vendors/grn/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/amendments': {
      id: '/_authenticated/amendments'
      path: '/amendments'
      fullPath: '/amendments'
      preLoaderRoute: typeof AuthenticatedAmendmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/': {
      id: '/_authenticated/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof AuthenticatedMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/grn/new': {
      id: '/_authenticated/vendors/grn/new'
      path: '/vendors/grn/new'
      fullPath: '/vendors/grn/new'
      preLoaderRoute: typeof AuthenticatedVendorsGrnNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAmendmentsRoute: typeof AuthenticatedAmendmentsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedMaterialsIndexRoute: typeof AuthenticatedMaterialsIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedVendorsGrnNewRoute: typeof AuthenticatedVendorsGrnNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmendmentsRoute: AuthenticatedAmendmentsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedMaterialsIndexRoute: AuthenticatedMaterialsIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedVendorsGrnNewRoute: AuthenticatedVendorsGrnNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
